// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VictuZ_2._0.Data;

#nullable disable

namespace VictuZ_2._0.Migrations
{
    [DbContext(typeof(SessionDbContext))]
    [Migration("20240920143031_AddSessionToDb")]
    partial class AddSessionToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VictuZ_2._0.Models.Sessions.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityDate = new DateTime(2024, 9, 20, 16, 30, 31, 387, DateTimeKind.Local).AddTicks(9180),
                            CreatedById = 1,
                            Description = "Dit is een voorbeeld",
                            EndDate = new DateTime(2024, 9, 20, 17, 30, 31, 387, DateTimeKind.Local).AddTicks(9231),
                            LocationId = 1,
                            Title = "Voorbeeld"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
